-- schema.sql — the three-table model. SQLite syntax (Postgres-compatible with
-- trivial type tweaks). Run once to create the store.
--
-- profiles : what each phone IS (static + pooled data + your overall verdict)
-- runs     : what each phone DID (resolved actions, timings, run health)
-- outcomes : what YOU DECIDED about it (manual verdict, linked back to runs)
--
-- The link outcomes.run_id -> runs.run_id (nullable) is what lets you stamp a
-- verdict at BOTH levels and keeps every "success" wired to the actions that
-- earned it — the raw material for the derived "success profile".

CREATE TABLE IF NOT EXISTS profiles (
    profile_key           TEXT PRIMARY KEY,
    geelark_profile_id    TEXT NOT NULL,
    business_name         TEXT NOT NULL,
    home_lat              REAL NOT NULL,
    home_lng              REAL NOT NULL,
    business_lat          REAL NOT NULL,
    business_lng          REAL NOT NULL,
    nearby_points         TEXT,            -- pipe-delimited pool of "lat,lng"
    nearby_points_backup  TEXT,            -- secondary pool (varied fallback)
    onsite_points         TEXT,            -- onsite pool for 30% origin split
    branded_keywords      TEXT,            -- pipe-delimited
    search_keywords       TEXT,            -- pipe-delimited
    business_goal         TEXT DEFAULT 'review',
    profile_verdict       TEXT DEFAULT 'pending',  -- success | unsuccess | pending
    provisioned           INTEGER DEFAULT 0,       -- verified via dumpsys: Fake GPS is mock provider
    maps_verified         INTEGER DEFAULT 0        -- BEHAVIOUR-based: Maps opens to usable search screen, NO Play Store interstitial
);

CREATE TABLE IF NOT EXISTS runs (
    run_id              TEXT PRIMARY KEY,   -- UUID, generated by resolver
    profile_key         TEXT NOT NULL REFERENCES profiles(profile_key),
    created_at          TEXT NOT NULL,      -- ISO timestamp, set before trigger
    rng_seed            INTEGER NOT NULL,   -- reproduce the exact plan
    -- resolved plan (what Python chose) --
    gps_lat             REAL,
    gps_lng             REAL,
    search_term_used    TEXT,
    branded_term_used   TEXT,
    fallback_taken      TEXT,               -- e.g. 'gps->backup_pool' or NULL
    -- run health (filled in after execution) --
    status              TEXT,               -- success | failed | failed_infra | skipped_data_error
    duration_seconds    REAL,
    interactions_fired  TEXT,               -- e.g. 'photos,reviews,call'
    failed_step         TEXT,               -- on failure
    screenshot_url      TEXT,               -- on failure
    finished_at         TEXT,
    -- GPS evidence (Section 9.12) --
    gps_verified        INTEGER DEFAULT 0,  -- 1 = dumpsys matched resolver coords
    gps_dumpsys_coords  TEXT,               -- what dumpsys reported
    -- Maps behavioural evidence (Section 9.12) --
    maps_task_status    INTEGER,            -- Geelark task status (3=completed, 4=failed)
    maps_foreground     TEXT,               -- foreground package after Maps flow
    search_submitted    INTEGER DEFAULT 0,  -- 1 = results list appeared (uiautomator evidence)
    business_found      INTEGER DEFAULT 0,  -- 1 = business name found on screen
    business_name_matched TEXT,             -- exact text that matched
    card_opened         INTEGER DEFAULT 0,  -- 1 = business knowledge panel was open (not route screen)
    interactions_present TEXT,              -- comma-separated: Photos,Reviews,Directions
    interaction_ip       TEXT               -- proxy IP used for this interaction (audit trail)
);

CREATE INDEX IF NOT EXISTS idx_runs_profile ON runs(profile_key, created_at);

CREATE TABLE IF NOT EXISTS outcomes (
    outcome_id      TEXT PRIMARY KEY,       -- UUID
    profile_key     TEXT NOT NULL REFERENCES profiles(profile_key),
    run_id          TEXT REFERENCES runs(run_id),  -- NULL = profile-level verdict
    verdict         TEXT NOT NULL,          -- success | unsuccess | pending
    ranking_observed TEXT,                  -- optional: what you saw on Google
    notes           TEXT,
    recorded_by     TEXT,
    recorded_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_outcomes_profile ON outcomes(profile_key);
CREATE INDEX IF NOT EXISTS idx_outcomes_run ON outcomes(run_id);

-- The "what has this phone done?" view used before deciding to re-run:
--   SELECT created_at, status, search_term_used, gps_lat, gps_lng,
--          interactions_fired, duration_seconds, fallback_taken
--   FROM runs WHERE profile_key = ? ORDER BY created_at DESC;

-- The "success profile" (descriptive aggregation over winning runs):
--   SELECT COUNT(*) AS winning_runs,
--          AVG(duration_seconds) AS avg_duration
--   FROM runs r JOIN outcomes o ON o.run_id = r.run_id
--   WHERE o.verdict = 'success';
