"""
test_resolver.py — Unit tests for the pure correctness core.

Run from the repo root:
    python3 -m pytest tests/ -v
or without pytest:
    python3 tests/test_resolver.py

These tests need NO network and NO Geelark. They lock down the behaviour that
matters most: the two-delimiter rule, coordinate integrity, the fallback chain,
reproducibility, and graceful degradation on bad data.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

import os
import tempfile

from data_layer import (
    Coordinate,
    DataError,
    profile_from_row,
    load_profiles_csv,
    load_profile_csv_by_key,
    _parse_coord,
    _split_pool,
)
from provisioning import check_phone_fit, ProvisioningError
from resolver import resolve


def _row(**overrides):
    base = {
        "profile_key": "Test_01",
        "geelark_profile_id": "GL-TEST",
        "business_name": "Test Biz",
        "home_lat": "51.5",
        "home_lng": "-0.12",
        "business_lat": "51.501",
        "business_lng": "-0.088",
        "nearby_points": "51.5224,-0.1026|51.5187,-0.0991",
        "nearby_points_backup": "51.5198,-0.1011",
        "branded_keywords": "Test Biz near me",
        "search_keywords": "thing one|thing two|thing three",
        "business_goal": "review",
        "profile_verdict": "pending",
        "provisioned": "false",
        "maps_verified": "false",
    }
    base.update(overrides)
    return base


# ---------- Two-delimiter rule: the coordinate must never be torn ----------

def test_coord_stays_intact_through_parsing():
    p = profile_from_row(_row())
    # Two points, each with its lat,lng glued together.
    assert len(p.nearby_points) == 2
    assert p.nearby_points[0].lat == 51.5224
    assert p.nearby_points[0].lng == -0.1026
    # The token round-trips with the comma inside.
    assert p.nearby_points[0].as_token() == "51.5224,-0.1026"


def test_pipe_separates_comma_does_not():
    pool = _split_pool("51.5224,-0.1026|51.5187,-0.0991|51.5203,-0.1044")
    assert pool == ["51.5224,-0.1026", "51.5187,-0.0991", "51.5203,-0.1044"]
    # Each item still contains exactly one comma (lat,lng intact).
    assert all(item.count(",") == 1 for item in pool)


def test_bad_coordinate_rejected():
    try:
        _parse_coord("not-a-coord")
        assert False, "should have raised"
    except DataError:
        pass


def test_latitude_out_of_range_rejected():
    try:
        _parse_coord("999.0,-0.1")
        assert False, "should have raised"
    except DataError:
        pass


# ---------- Required fields ----------

def test_missing_business_name_is_fatal():
    try:
        profile_from_row(_row(business_name=""))
        assert False, "should have raised"
    except DataError:
        pass


# ---------- Reproducibility ----------

def test_same_seed_same_plan():
    p = profile_from_row(_row())
    a = resolve(p, seed=42)
    b = resolve(p, seed=42)
    assert (a.gps_lat, a.gps_lng, a.search_term, a.branded_term) == \
           (b.gps_lat, b.gps_lng, b.search_term, b.branded_term)


def test_seed_is_recorded_when_autogenerated():
    p = profile_from_row(_row())
    plan = resolve(p)  # no seed
    # The autogenerated seed is captured so the run can be replayed.
    replay = resolve(p, seed=plan.rng_seed)
    assert (replay.gps_lat, replay.gps_lng, replay.search_term) == \
           (plan.gps_lat, plan.gps_lng, plan.search_term)


# ---------- Fallback chain ----------

def test_gps_uses_primary_pool_normally():
    p = profile_from_row(_row())
    plan = resolve(p, seed=1)
    primary = {c.as_token() for c in p.nearby_points}
    assert f"{plan.gps_lat},{plan.gps_lng}" in primary
    assert plan.fallbacks_taken == []


def test_gps_falls_back_to_backup_pool_when_primary_empty():
    p = profile_from_row(_row(nearby_points=""))
    plan = resolve(p, seed=1)
    backup = {c.as_token() for c in p.nearby_points_backup}
    assert f"{plan.gps_lat},{plan.gps_lng}" in backup
    assert "gps->backup_pool" in plan.fallbacks_taken


def test_gps_falls_back_to_business_when_both_pools_empty():
    p = profile_from_row(_row(nearby_points="", nearby_points_backup=""))
    plan = resolve(p, seed=1)
    assert (plan.gps_lat, plan.gps_lng) == (p.business.lat, p.business.lng)
    assert "gps->business_coord" in plan.fallbacks_taken


def test_empty_search_pool_aborts_run():
    p = profile_from_row(_row(search_keywords=""))
    plan = resolve(p, seed=1)
    assert plan.abort is True
    assert plan.search_term is None
    assert plan.abort_reason is not None


def test_empty_branded_pool_skips_not_aborts():
    p = profile_from_row(_row(branded_keywords=""))
    plan = resolve(p, seed=1)
    assert plan.abort is False
    assert plan.branded_term is None


# ---------- Graceful degradation ----------

def test_single_item_pool_is_stable_not_an_error():
    p = profile_from_row(_row(nearby_points="51.5224,-0.1026"))
    plan = resolve(p, seed=7)
    assert (plan.gps_lat, plan.gps_lng) == (51.5224, -0.1026)
    assert plan.abort is False


def test_avoid_gps_prevents_repeat_when_pool_allows():
    p = profile_from_row(_row())  # two-item primary pool
    first = p.nearby_points[0]
    # Ask resolver to avoid the first point; with 2 items it must pick the other.
    plan = resolve(p, seed=1, avoid_gps=first)
    assert f"{plan.gps_lat},{plan.gps_lng}" != first.as_token()


def test_bad_token_in_pool_dropped_with_warning_not_fatal():
    p = profile_from_row(_row(nearby_points="51.5224,-0.1026|garbage|51.5187,-0.0991"))
    assert len(p.nearby_points) == 2  # garbage dropped
    assert any("dropped bad coordinate" in w for w in p.warnings)


# ---------- Data-binding guards: load-time duplicate / missing / match checks ----------

def _write_temp_csv(content: str) -> str:
    with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False) as f:
        f.write(content)
        return f.name


def test_duplicate_profile_key_aborts_at_load_time():
    header = "profile_key,geelark_profile_id,business_name,home_lat,home_lng,business_lat,business_lng,nearby_points,nearby_points_backup,branded_keywords,search_keywords,business_goal,profile_verdict\n"
    csv = header + "Dup_01,GL-1,Biz A,51.5,-0.12,51.501,-0.088,,,,,,review,pending\n"
    csv += "Dup_01,GL-2,Biz B,51.5,-0.12,51.501,-0.088,,,,,,review,pending\n"
    path = _write_temp_csv(csv)
    try:
        load_profiles_csv(path)
        assert False, "should have raised DataError for duplicate key"
    except DataError as e:
        assert "Dup_01" in str(e)
        assert "Duplicate" in str(e)
    finally:
        os.unlink(path)


def test_missing_profile_key_aborts_at_load_time():
    header = "profile_key,geelark_profile_id,business_name,home_lat,home_lng,business_lat,business_lng,nearby_points,nearby_points_backup,branded_keywords,search_keywords,business_goal,profile_verdict\n"
    csv = header + ",GL-1,Biz A,51.5,-0.12,51.501,-0.088,,,,,,review,pending\n"
    path = _write_temp_csv(csv)
    try:
        load_profiles_csv(path)
        assert False, "should have raised DataError for missing key"
    except DataError as e:
        assert "Missing" in str(e) or "profile_key" in str(e).lower()
    finally:
        os.unlink(path)


def test_zero_match_aborts():
    header = "profile_key,geelark_profile_id,business_name,home_lat,home_lng,business_lat,business_lng,nearby_points,nearby_points_backup,branded_keywords,search_keywords,business_goal,profile_verdict\n"
    csv = header + "Only_01,GL-1,Biz A,51.5,-0.12,51.501,-0.088,,,,,,review,pending\n"
    path = _write_temp_csv(csv)
    try:
        load_profile_csv_by_key(path, "Missing_01")
        assert False, "should have raised DataError for zero match"
    except DataError as e:
        assert "Missing_01" in str(e)
        assert "not found" in str(e)
    finally:
        os.unlink(path)


def test_exactly_one_match_succeeds():
    header = "profile_key,geelark_profile_id,business_name,home_lat,home_lng,business_lat,business_lng,nearby_points,nearby_points_backup,branded_keywords,search_keywords,business_goal,profile_verdict\n"
    csv = header + "Only_01,GL-1,Biz A,51.5,-0.12,51.501,-0.088,,,,,,review,pending\n"
    path = _write_temp_csv(csv)
    try:
        p = load_profile_csv_by_key(path, "Only_01")
        assert p.profile_key == "Only_01"
        assert p.geelark_profile_id == "GL-1"
    finally:
        os.unlink(path)


# ---------- Provisioning / maps_verified gate (Section 9.10) ----------

def test_provisioned_false_blocks_run():
    p = profile_from_row(_row(provisioned="false", maps_verified="true"))
    fit, reason = check_phone_fit(p)
    assert fit is False
    assert "not provisioned" in reason
    assert p.profile_key in reason


def test_maps_verified_false_blocks_run():
    p = profile_from_row(_row(provisioned="true", maps_verified="false"))
    fit, reason = check_phone_fit(p)
    assert fit is False
    assert "maps not verified" in reason
    assert "Play Store" in reason  # behaviour-based warning
    assert p.profile_key in reason


def test_both_provisioned_and_maps_verified_allows_run():
    p = profile_from_row(_row(provisioned="true", maps_verified="true"))
    fit, reason = check_phone_fit(p)
    assert fit is True
    assert reason == ""


def test_provisioning_fields_parse_from_csv():
    header = "profile_key,geelark_profile_id,business_name,home_lat,home_lng,business_lat,business_lng,nearby_points,nearby_points_backup,branded_keywords,search_keywords,business_goal,profile_verdict,provisioned,maps_verified\n"
    csv = header + "Prov_01,GL-1,Biz A,51.5,-0.12,51.501,-0.088,,,,,review,pending,true,false\n"
    path = _write_temp_csv(csv)
    try:
        p = load_profile_csv_by_key(path, "Prov_01")
        assert p.provisioned is True
        assert p.maps_verified is False
    finally:
        os.unlink(path)


def _run_all():
    import inspect
    mod = sys.modules[__name__]
    tests = [v for k, v in vars(mod).items() if k.startswith("test_") and callable(v)]
    passed = 0
    for t in tests:
        t()
        passed += 1
        print(f"  PASS  {t.__name__}")
    print(f"\n{passed}/{len(tests)} tests passed.")


if __name__ == "__main__":
    _run_all()
